In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

dataset = pd.read_csv('Exasens.csv')

X = dataset.iloc[:,[1,2,3]].values
Y = dataset.iloc[:,-1].values
print(X)dataset = dataset.replace('HC',0)dataset = dataset.replace('COPD',1)

[[0 2 1]
 [0 2 2]
 [0 2 2]
 [0 2 1]
 [0 3 1]
 [0 2 2]
 [0 1 1]
 [0 1 2]
 [0 1 3]
 [0 2 3]
 [0 3 1]
 [0 1 1]
 [0 2 1]
 [0 2 2]
 [1 2 1]
 [0 2 2]
 [1 2 2]
 [1 1 2]
 [0 1 1]
 [0 1 3]
 [0 2 1]
 [0 1 1]
 [1 2 2]
 [0 1 1]
 [0 1 1]
 [1 2 1]
 [1 1 1]
 [0 2 1]
 [1 2 3]
 [1 2 1]
 [0 1 1]
 [0 2 1]
 [0 2 2]
 [0 1 1]
 [0 1 1]
 [0 2 3]
 [0 2 3]
 [0 2 2]
 [0 1 1]
 [0 2 2]
 [0 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [0 2 1]
 [0 1 1]
 [0 2 2]
 [0 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 1]
 [1 3 2]
 [1 2 1]
 [0 2 1]
 [1 1 3]
 [0 2 1]
 [1 2 1]
 [1 2 2]
 [1 1 1]
 [1 1 3]
 [0 1 1]
 [0 3 3]
 [1 2 3]
 [1 3 1]
 [1 2 3]
 [1 2 2]
 [1 1 1]
 [1 2 3]
 [1 2 2]
 [1 2 2]
 [1 1 3]
 [1 2 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 2 1]
 [0 1 2]
 [0 1 1]
 [0 1 3]
 [0 2 1]
 [0 1 3]
 [0 2 3]
 [0 1 3]
 [1 2 3]
 [0 1 3]
 [0 1 1]
 [0 2 3]
 [0 2 2]
 [1 2 3]
 [1 3 1]
 [0 2 1]
 [0 2 3]
 [0 2 1]
 [0 2 1]
 [0 2 1]
 [0 1 1]
 [0 1 1]
 [0 1 2]
 [0 1 1]
 [0 2 1]
 [1 3 1]
 [0 2 2]
 [0 1 1]
 [0 1 1]
 [0 1 3]
 [0 1 3]
 [0 1 2]
 